steps:
  # API
  - name: 'gcr.io/cloud-builders/docker'
    id: api-docker-build
    args:
      - 'build'
      - '--tag=${_API_IMAGE}'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    id: api-docker-push
    args:
      - 'push'
      - '${_API_IMAGE}'
  # apps
  - name: 'hashicorp/terraform'
    id: terraform-apply-apps
    dir: infra/deployment/terraform/apps
    script: |
      terraform init -backend-config=bucket=$TFSTATE_BUCKET

      terraform apply --auto-approve
    env:
      - 'TFSTATE_BUCKET=${_TFSTATE_BUCKET}'
      - 'TF_VAR_project_id=${PROJECT_ID}'
      - 'TF_VAR_region=${_REGION}'
      - 'TF_VAR_api_image=${_API_IMAGE}'
      - 'TF_VAR_api_sa_email=${_API_SA_EMAIL}'
      - 'TF_VAR_api_domain_name=${_API_DOMAIN_NAME}'
      - 'TF_VAR_alerting_emails=${_ALERTING_EMAILS}'
options:
  logging: CLOUD_LOGGING_ONLY
