// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj1u7l4h77kJmK66m0hG5bB_4KQnEqy74',
    appId: '1:136183611397:web:64a60708f81a30e4319c6c',
    messagingSenderId: '136183611397',
    projectId: 'hellomyfriendo-production',
    authDomain: 'hellomyfriendo-production.firebaseapp.com',
    storageBucket: 'hellomyfriendo-production.appspot.com',
    measurementId: 'G-JNQ1EN66Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUvzPraI6KEGeg4GsVAuO7oAnGhykD5_g',
    appId: '1:136183611397:android:0b061bca4e8fc7d4319c6c',
    messagingSenderId: '136183611397',
    projectId: 'hellomyfriendo-production',
    storageBucket: 'hellomyfriendo-production.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCyh4xMjW_en3JUYJpTUbxbLCt3JBykp0',
    appId: '1:136183611397:ios:35a7a5a4281f287d319c6c',
    messagingSenderId: '136183611397',
    projectId: 'hellomyfriendo-production',
    storageBucket: 'hellomyfriendo-production.appspot.com',
    androidClientId: '136183611397-v9rhsl4uj3luse3bg1snrpnif2aiiac5.apps.googleusercontent.com',
    iosClientId: '136183611397-rl2qslueh5ucctkir334aal7u3i4hcr9.apps.googleusercontent.com',
    iosBundleId: 'com.hellomyfriendo.hellomyfriendo',
  );
}
