// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBFbQQo1L7ppUajbBJKO4z6Ya_JLpw3-Y',
    appId: '1:136183611397:web:96ae39770dda033c319c6c',
    messagingSenderId: '136183611397',
    projectId: 'hellomyfriendo-production',
    authDomain: 'hellomyfriendo-production.firebaseapp.com',
    storageBucket: 'hellomyfriendo-production.appspot.com',
    measurementId: 'G-0SDPK369QT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1rz7Vs7W3KP6xZWveFg9MpUnL8Byw3UY',
    appId: '1:136183611397:android:47079c21abdffd79319c6c',
    messagingSenderId: '136183611397',
    projectId: 'hellomyfriendo-production',
    storageBucket: 'hellomyfriendo-production.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2tagYZPKzSmLwDAUuE0fKxyj5NnXh5q8',
    appId: '1:136183611397:ios:67455fe0c79193e3319c6c',
    messagingSenderId: '136183611397',
    projectId: 'hellomyfriendo-production',
    storageBucket: 'hellomyfriendo-production.appspot.com',
    androidClientId:
        '136183611397-274bdadcr41r5p2apdic526ke6e14rru.apps.googleusercontent.com',
    iosClientId:
        '136183611397-qj5r1ig2a3mk6o1h54706m75t2ds5nqn.apps.googleusercontent.com',
    iosBundleId: 'com.hellomyfriendo.hellomyfriendo',
  );
}
