version: '3.9'
services:
  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - PORT=${PORT}
      - K_REVISION=${K_REVISION}
      - K_SERVICE=${K_SERVICE}
      - FRIENDS_V1_FIRESTORE_FRIENDSHIPS_COLLECTION=${FRIENDS_V1_FIRESTORE_FRIENDSHIPS_COLLECTION}
      - FRIENDS_V1_FIRESTORE_FRIEND_REQUESTS_COLLECTION=${FRIENDS_V1_FIRESTORE_FRIEND_REQUESTS_COLLECTION}
      - USERS_V1_FIRESTORE_USERS_COLLECTION=${USERS_V1_FIRESTORE_USERS_COLLECTION}
      - WANTS_V1_FIRESTORE_WANTS_COLLECTION=${WANTS_V1_FIRESTORE_WANTS_COLLECTION}
      - WANTS_V1_STORAGE_WANTS_ASSETS_BUCKET=${WANTS_V1_STORAGE_WANTS_ASSETS_BUCKET}
    depends_on:
      firestore_emulator:
        condition: service_healthy
  firestore_emulator:
    image: 'mtlynch/firestore-emulator'
    ports:
      - 9200:9200
    environment:
      - FIRESTORE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - PORT=9200
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://firestore_emulator:9200']
      interval: 5s
      timeout: 5s
      retries: 10
