version: '3.9'
services:
  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      - PGHOST=database
      - PGPORT=${PGPORT}
      - PGUSERNAME=${PGUSERNAME}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - PORT=${PORT}
      - K_REVISION=${K_REVISION}
      - K_SERVICE=${K_SERVICE}
    depends_on:
      database:
        condition: service_healthy
  database:
    image: 'postgres:15'
    ports:
      - ${PGPORT}:${PGPORT}
    environment:
      - POSTGRES_USER=${PGUSERNAME}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
